[FABN-1564] SubjectDN extensibility
hyperledger/fabric-sdk-node pull request #264
Opened 2020-06-27 02:00 UTC by davidkhala

In multiple places we have only common name as input for building X509
Subject.
We should allow directly full input of subject

Signed-off-by: david <david-khala@hotmail.com>

2020-07-21 15:02 UTC, bestbeforetoday requested changes
Generally looks good to me. Just some minor tweaks

2020-07-21 15:02 UTC, bestbeforetoday commented on fabric-ca-client/test/FabricCAServices.js
> +			getSubjectStub.returns('mr_penguin');
The return value should probably be `/CN=mr_penguin` to make it a valid subject string. I know it doesn't break the code today but might confuse somebody in the future if they change the code do something with the subject and all these tests start failing.

2020-07-21 15:02 UTC, bestbeforetoday commented on fabric-ca-client/lib/helper.js
> +const getSubjectCommonName = (pem) => {
I don't _think_ this is used anywhere. if not, might as well remove it. Just be careful to make sure the corresponding unit tests still drive `getSubject()` instead where appropriate.

2020-07-21 15:25 UTC, davidkhala commented on fabric-ca-client/lib/FabricCAServices.js
> +	 * @property {string} subject - Optional. The X509 Subject to use in generating CSR inline
Definitely

2020-07-21 15:27 UTC, davidkhala commented
> Generally looks good to me. Just some minor tweaks

Thanks again. Agree all all feedback. WIP

2020-07-29 13:12 UTC, bestbeforetoday approved these changes

2020-07-29 13:12 UTC, merged