[bug-fix] eventhub status value is now interpreted as http code
hyperledger/fabric-sdk-node pull request #480
Opened 2021-08-06 03:38 UTC by davidkhala

instead of string like "NOT_FOUND", we see the actual value is 404
Signed-off-by: DavidLiu <david.yx.liu@oracle.com>

2021-08-06 04:41 UTC, davidkhala commented
along the way, I want to migrate from a deprecated jsrsasign method. 

Reference is [here](https://github.com/kjur/jsrsasign/blob/f3d70198b2d923bdeacd2bd8c60605a96101d802/src/asn1csr-1.0.js#L325)

2021-08-12 15:39 UTC, bestbeforetoday commented
> along the way, I want to migrate from a deprecated jsrsasign method.
> 
> Reference is [here](https://github.com/kjur/jsrsasign/blob/f3d70198b2d923bdeacd2bd8c60605a96101d802/src/asn1csr-1.0.js#L325)
> 
> **EDIT**: we find this method is new and does not exist in jsrsasign 8, rollback first

It would be great to move to the most current version of jsrsasign but API changes mean we're stuck at v8 unless the SDK code is updated to reflect the newer API

2021-08-12 15:50 UTC, bestbeforetoday requested changes
It's a shame no scenario tests pick up this problem as then we're sure we match runtime behaviour rather than just values injected by unit tests.

It would look clearer to me to use the protobuf definitions rather than hard-code the status values, so I think that's worth changing (see comments). Otherwise looks OK to me.

2021-08-13 01:12 UTC, davidkhala commented on fabric-common/test/EventService.js
> +			onStub.yields({Type: 'status', status: 404});
Indeed, will do

2021-08-13 09:15 UTC, davidkhala commented
> > along the way, I want to migrate from a deprecated jsrsasign method.
> > Reference is [here](https://github.com/kjur/jsrsasign/blob/f3d70198b2d923bdeacd2bd8c60605a96101d802/src/asn1csr-1.0.js#L325)
> > **EDIT**: we find this method is new and does not exist in jsrsasign 8, rollback first
> 
> It would be great to move to the most current version of jsrsasign but API changes mean we're stuck at v8 unless the SDK code is updated to reflect the newer jsrsasign API

Noted and will do it later.

2021-08-13 09:36 UTC, bestbeforetoday approved these changes

2021-08-13 09:36 UTC, merged