[refactor] use override than type check switch
hyperledger/fabric-sdk-node pull request #512
Opened 2021-10-11 04:01 UTC by davidkhala

An attempt to move if type=='query' check code block to inherit class
instead of expose too much subclass implementation detail in superclass

Signed-off-by: DavidLiu <david.yx.liu@oracle.com>

2021-10-13 09:50 UTC, davidkhala commented
@bestbeforetoday Hi Mark, ready to review

BTW, I would like to extend our discussion on the how should a handler function works.

2021-10-13 16:12 UTC, bestbeforetoday requested changes
Moving the Query-specific logic out to the Query class looks like a good change to me. Just a couple of tweaks that I think are worth making.

2021-10-15 08:24 UTC, bestbeforetoday requested changes
Just the one issue with duplicate constant string to resolve and it looks good.

2021-10-19 08:44 UTC, bestbeforetoday approved these changes

2021-10-19 08:44 UTC, merged