FABN-1452 NodeSDK add fabric-common doc
hyperledger/fabric-sdk-node pull request #96
Opened 2020-01-23 01:39 UTC by harrisob

Add fabric-common class doc and include updates to tutorials
with the removal of fabric-client details.

Signed-off-by: Bret Harrison <beharrison@nc.rr.com>

2020-01-23 13:27 UTC, heatherlp commented on docs/index.md
> +* **fabric-common**: Provides APIs to interact with the core components of a Hypreledger Fabric-based blockchain network, namely the peers, orderers and event streams.
Hypreledger sounds premature :)

2020-01-23 14:54 UTC, heatherlp requested changes
Looks good - just some typos

2020-01-23 14:54 UTC, heatherlp commented on docs/tutorials/sign-transaction-offline.md
> +The `fabric-common` comes with the ability to sign a transaction outside of
The `fabric-common` package?

2020-01-23 22:06 UTC, harrisob commented on docs/index.md
> +* **fabric-common**: Provides APIs to interact with the core components of a Hypreledger Fabric-based blockchain network, namely the peers, orderers and event streams.
fixed

2020-01-23 22:16 UTC, harrisob commented on docs/tutorials/handlers.md
> +The included handler was designed to be used with discovery to provided automatic
fixed

2020-01-23 22:16 UTC, harrisob commented on docs/tutorials/handlers.md
> +to the `send` method of the service in the optons object attribute `handler`.
fixed

2020-01-23 22:17 UTC, harrisob commented on docs/tutorials/sign-transaction-offline.md
> +The `fabric-common` comes with the ability to sign a transaction outside of
fixed

2020-01-24 09:39 UTC, heatherlp approved these changes
LGTM - thanks

2020-01-24 09:40 UTC, merged